### ISSUE TITLE
Meta Tag

### ISSUE THREAD

**Issue by MattHelton** [Owlalert1/splurty-new#1]
Add a meta tag to your `app/views/layouts/application.html.erb` file so your site looks good on mobile devices.
It should look like this:
`<meta name="viewport" content="width=device-width, initial-scale=1">`

**Comment by Owlalert1** [comment]
Added meta tag per suggestion from Matt and it made a huge difference on how my app looks on mobile devices.  Much better!  Thanks for the tip.
